# Generated by Django 4.2.5 on 2023-11-05 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='uploads/categories/')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Номинация',
                'verbose_name_plural': 'Номинации',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Изображение')),
                ('copyright', models.BooleanField(verbose_name='Вы являетесь правообладателем?')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на публикацию VK')),
                ('name_work', models.CharField(blank=True, max_length=100, verbose_name='Название работы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание работы')),
                ('photo_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место съемки')),
                ('processing', models.BooleanField(verbose_name='Подвергалось ли фото обработке?')),
                ('model_release', models.CharField(blank=True, max_length=150, null=True, verbose_name='Модельный релиз')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('vote_count', models.IntegerField(default=0, editable=False, verbose_name='Проголосовавших')),
                ('photo_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contest.category', verbose_name='Номинация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор работы')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
    ]
