# Generated by Django 4.2.5 on 2023-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Номинацию', 'verbose_name_plural': 'Номинации'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Работу', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AddField(
            model_name='photo',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Прошло модерацию'),
        ),
    ]
